version: '3'
services:

  container_b:
    build:
      context: ./ContainerB
    ports:
      - "8081:80"
    depends_on:
      - container_a
      - container_c

  container_a:
    build:
      context: ./ContainerA
    environment:
      INTERVAL: 300
    depends_on:
      - container_c

  container_c:
    build:
      context: ./ContainerC # Replace with the actual build context for ContainerC
