version: '3'
services:

  container_a:
    image: container_a:latest
    environment:
      INTERVAL: 300
    depends_on:
      - container_c
    restart: on-failure

  container_b:
    image: container_b:latest
    ports:
      - "8080:5000"
    depends_on:
      - container_a
      - container_c
    restart: on-failure

  container_c:
    image: container_c:latest
    ports:
    - "15672:15672"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5


